### ISSUE TITLE
Quotes missing from compiled css

### ISSUE THREAD

**Issue by mrmrs** [tachyons-css/tachyons-font-family#1]
Haven't dug into this yet but it seems that quotes are being stripped from minified css version of the module.

Example:

```
.sans-serif{font-family:-apple-system,avenir next,avenir,Roboto,helvetica,helvetica neue,arial,sans-serif}.serif{font-family:times,TimesNewRoman,Times New Roman,georgia,serif}.code,code{font-family:Consolas,monaco,monospace}.helvetica{font-family:helvetica,helvetica neue,arial,sans-serif}.georgia{font-family:georgia,serif}.times{font-family:Times,TimesNewRoman,Times New Roman,serif}.bodoni{font-family:Bodoni MT,serif}.calisto{font-family:Calisto MT,serif}.garamond{font-family:Garamond,serif}
```

In font-family declarations this is an issue as you need quotes around any names that contain a space.

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
